language: node_js

node_js:
  - stable

services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: hello_world_test
  MYSQL_ROOT_PASSWORD: root


install:
  - npm install
  
script:
  - jest
    
